### PR TITLE
v5.4.3

### PR DESCRIPTION
**Pull request by sjpfenninger**
Trying to see whether I can get around the build errors in #14

### CODE REVIEW

**Comment by sjpfenninger** [comment]
@whart222 @jsiirola It seems that if pyutilib 5.6.2 were available on conda-forge, then this could build. Any chance of merging conda-forge/pyutilib-feedstock#12 and then this?

**Comment by whart222** [comment]
I'll work on this in the next few days

**Comment by sjpfenninger** [comment]
@whart222 Looks like the package now builds successfully with pyutilib 5.6.2 on all platforms -- perhaps check if what I've removed in ``recipe.yaml`` works for you, then either let me know what to change or merge this?

**Comment by whart222** [comment]
@jsiirola Should we cut a new Pyomo release to address the Python2 print statements in GDP?

**Comment by jsiirola** [comment]
I think a 5.4.4 release might make sense before the expression merge. There continues to be development in both GDP and in some of the solver interfaces. We also need to fix the incompatibility with GLPK 4.65, too. 

Should we set up a project board to prepare? I think a horizon in the next week or two would be good.

**Comment by sjpfenninger** [comment]
@jsiirola @whart222 As 5.4.3 is the most recent version on PyPI anyway, and we'd like to release a new version of [calliope-project/calliope](https://github.com/calliope-project/calliope) with it as a dependency (it fixes some issues we have with earlier versions), it would be really useful if we could already have this version on conda-forge irrespective of 5.4.4 release plans.

**Comment by whart222** [comment]
@jsiirola If we're holding up another project, I'm inclined to merge this PR now.  We can plan/manage a 5.4.4 release separately.  Looking at the changes in the meta.yaml file, I don't see anything that would be problematic.  Thoughts?

**Comment by jsiirola** [comment]
Agreed. I was assuming the 5.4.4 discussion was in addition to the current 5.4.3 release. 

@whart222, it should be pretty to cut the 5.4.3 Conda release now, yes?

**Comment by whart222** [comment]
@sjpfenninger Can you describe the motivation for commenting out the SMPS stuff?  Were there similar issues with print statements?  Or something else that we should correct?

**Comment by sjpfenninger** [comment]
@whart222 Thanks for merging! During the import tests, I get ``ModuleNotFoundError: No module named 'pyomo.pysp.smps'``, which is why I had removed the smps stuff for the package to actually build. Not sure why that's happening though..

**Pull request merged**
